[build]
  command = ""                     
  publish = ""                     
  functions = "netlify/functions"  # директорія з функціями

[dev]
  functions = "netlify/functions"  # Netlify dev шукатиме функції тут
  publish = ""                     
  port = 8888                      # локальний порт
